services:
  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: core
      POSTGRES_PASSWORD: core
      POSTGRES_DB: evaluation_platform
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 15432:5432
volumes:
  pgdata: