create table if not exists memberships
(
    id                  bigint generated by default as identity
        primary key,
    user_id             bigint references hef_users,
    workspace_id        bigint references workspaces,
    next_question_id    bigint references questions,
    current_question_id bigint references questions
);

alter table memberships
    owner to core;

create unique index if not exists memberships_user_id_workspace_id on memberships (user_id, workspace_id);
